standardise some function error messages

diff --git a/src/public/stage b/src/public/stage
--- a/src/public/stage
+++ b/src/public/stage
@@ -18,27 +18,28 @@ fi
 local -r _err=$(mktemp -q -t "${0}") \
 	msg="Staging ${curr_b}..."
 
-{ trap 'git checkout -q "${curr_b}"' INT TERM ERR
+() {
+	trap 'git checkout -q "${curr_b}"' INT TERM ERR
 	git checkout -q staging && \
 		git fetch -q && \
 		git reset -q --hard origin/staging && \
 		git merge -q --no-edit "${curr_b}" && \
 		git push -q origin staging && \
-		git checkout -q "${curr_b}"; } 2>"${_err}" & local -r pid="${!}"
+		git checkout -q "${curr_b}"
+} 2>"${_err}" & local -r pid="${!}"
 trap 'kill "${pid}"; rm -f "${_err}"; return 130' INT TERM
 
 _spinner "${pid}" "${msg}"
 
-if wait "${pid}" 2>/dev/null; then
-	printf "%s%s✓%s %s done\n" "${CR}${EL}" "${GREEN}" "${NS}" "${msg}"
-else
-	printf "%s%s×%s %s error\n" "${CR}${EL}" "${RED}" "${NS}" "${msg}"
+if ! wait "${pid}" 2>/dev/null; then
+	printf "%s%s %s error\n" "${CR}${EL}" "${BOLD}${RED}×${NS}" "${msg}"
 	if [[ -e "${_err}" && -s "${_err}" ]]; then
 		while read -r line; do
-			printf "  %s%s%s\n" "${DIM}" "${line}" "${NS}"
+			printf "  ${DIM}%s${NS}\n" "${line}"
 		done < <"${_err}"
 	fi
 	return 1
 fi
 
+printf "%s%s %s done\n" "${CR}${EL}" "${BOLD}${DIM}${GREEN}✓${NS}" "${DIM}${msg}${NS}"
 rm -f "${_err}"
